version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_NAME=Web HME Project
      - APP_ENV=local
      - APP_KEY=base64:10h1HWD1LWkfJoB6swlgApilGb08fdVHJds8q5j2PQM=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - LOG_CHANNEL=stack
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    depends_on:
      - mysql
    networks:
      - laravel-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel-network

  # PhpMyAdmin (Optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_password
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge
