# Nixpacks configuration for Railway.app deployment
[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "cp .env.example .env",
    "php artisan key:generate --force --no-interaction",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
