[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100
sleepApplication = false

[env]
NODE_ENV = "production"
